### ISSUE TITLE
Could you provide a quick tutorial about how to reproduce the experiments in the paper?

### ISSUE THREAD

**Issue by PennPanda** [kunglab/ddnn#2]
Dear authors,

I'm interested in reproducing the results in your paper. 
Could you provide a quick tutorial on how to reproduce the experiments in the paper?

Thanks,

**Comment by BradMcDanel** [comment]
Thanks for your interest in the paper. We are working on simplifying the code to get a minimal example of what is necessary to reproduce results.

**Comment by PennPanda** [comment]
Thank you so much! I'm looking forward to it!
Is there any timeline for this work?

**Comment by BradMcDanel** [comment]
I need to coordinate with Surat, as he wrote most of it, to figure out the timeline (I will update this when I know). Mainly, we just need to remove code that is unused and simplify the example.

**Comment by helloCloudWorld** [comment]
Thank you so much! I am looking forward to it too!

**Comment by mengzi0617** [comment]
非常感谢！我们都在期待！

**Comment by mengzi0617** [comment]
Thank you so much! We are all looking forword to it!

**Comment by Dearsunlight** [comment]
@PennPanda Hello, do you find out a way to start it?

**Comment by BradMcDanel** [comment]
Sorry for the delay. Please see the pytorch branch that was just added (and the quick start in the readme). It is a much more simplified code base and shows the basic structure. Currently, it is using standard image datasets (e.g., MNIST/CIFAR-10) subdivided into 6 smaller images which simulate the 6 end devices. I am working on porting the dataset over into pytorch to reproduce the paper results.

**Comment by Dearsunlight** [comment]
@BradMcDanel 
Dear author, thanks for your simplified code! I run the command "python evaluate.py --dataset mnist --model_path models/mnist.pth", but met the problem that " AttributeError: 'BatchNorm2d' object has no attribute 'track_running_stats' " as shown in the photo.
 
![image](https://user-images.githubusercontent.com/39198717/40564871-6c078c96-6038-11e8-8526-884b622173e4.png)
![image](https://user-images.githubusercontent.com/39198717/40564886-75753210-6038-11e8-8895-5143f4c5dd0f.png)

**Comment by BradMcDanel** [comment]
Which version of pytorch are you using. You can see by doing:
`
print(torch.__version__)
`
I am using 0.3.1.post2. It looks like 0.4 was released end of April which might break things. I will upgrade to 0.4 and rerun the mode.

**Comment by Dearsunlight** [comment]
you are right! I am using 0.4.0.

**Comment by BradMcDanel** [comment]
I should upgrade anyways. Please check back tomorrow and the model will be using 0.4.0.

**Comment by Dearsunlight** [comment]
Thank you for doing this!

**Comment by BradMcDanel** [comment]
I have updated the pytorch branch to use 0.4.0. Please try again. If it still does not work, please raise another issue with what is specifically work. Thanks!
