### ISSUE TITLE
Is there an  minimal example uploaded? 

### ISSUE THREAD

**Issue by linzihan-backforward** [kunglab/ddnn#3]
Dear author，
I am also interested in your research.
Nearly a month passed,I want to know will you upload a minimal example for us to reproduce the experiment? If so,what's the timeline?

Thanks,

**Comment by BradMcDanel** [comment]
Please see the pytorch branch that was just added. This should be much easier to follow. I am working on porting the dataset used in the paper over, but for now it is working with partitioned standard image datasets (e.g., MNIST/CIFAR-10). The exact model in the paper is slightly different (smaller), but the structure is exactly the same in net.py. Thanks for your interest.

**Comment by BradMcDanel** [comment]
For future more specific questions, please open new issues. Thanks!
