### ISSUE TITLE
What is the DDNN architecture?

### ISSUE THREAD

**Issue by lxbaoding** [kunglab/ddnn#4]
Dear author,
I am interested in your research.
I want to know what is the DDNN architecture according  to the paper named Distributed Deep Neural Networks over the Cloud, the Edge and End Devices. In this paper,you use two types of blocks: FC and   ConvP, so I also want know which part of the code represents FC block and Convp respectively.

**Comment by BradMcDanel** [comment]
For shorthand, I believe FC means a fully connected or linear layer and Convp means convolution + pooling.

**Comment by lxbaoding** [comment]
Thank you so much!
While building the device_model or cloud_model,what is the role of the parameter 'activation'?
