### ISSUE TITLE
Which code can run in the end devices?

### ISSUE THREAD

**Issue by yupeihua** [kunglab/ddnn#5]
Hi : I have problems about how to run this code
1. Which code will run in the end device ?
2. Which code is about the communication between end devices and cloud?

**Comment by charanrajt** [comment]
Hi, 
In the similar lines of the above questions, could you please upload the documentation for the code base?

**Comment by BradMcDanel** [comment]
Can you please check our pytorch branch, which gives a simple example of the distributed model structure. We plan to add more to this branch.

**Comment by charanrajt** [comment]
Can you please point me to the Pytorch branch link, I could not able to find it. 

Thanks,
Charan

**Comment by BradMcDanel** [comment]
Here it is: https://github.com/kunglab/ddnn/tree/pytorch

**Comment by charanrajt** [comment]
Thanks, appreciate the help.
